language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
    - python setup.py install
script:
    - mkdir tests_py3
    - 2to3 -w -n -o tests_py3 tests/*.py
    - nosetests -v --where=tests --py3where=tests_py3 -d --with-coverage --cover-package=beaker
