language: python
os:
  - linux
dist: xenial
services:
  - mongodb
  - memcached
  - redis-server
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
    - pip install -e .[testsuite]
script:
    - nosetests -v -d --with-coverage --cover-package=beaker
