language: python
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install -e .[testsuite]
script:
    - nosetests -v -d --with-coverage --cover-package=beaker
